# =====================================
# @Desc: springboot工程配置文件，使用yml方式
#        包括：server、datasource(druid)、jpa配置
# @Auther: andy.ten@tom.com
# @Date: 2020/08/08 9:39 上午
# @Version: v1.0.1
# =====================================

spring:
  profiles:
    active: dev

# 自定义属性
myprops:
  exectime:
    errtime: 3000
    warntime: 2000
